export default {
  GOOGLE_DOC: require('../assets/Images/google_doc.jpg'),
  SNT_DEFAULT: require('../assets/Images/SNT_DEFAULT.jpg'),
  TECHNICAL_TEST: require('../assets/Images/technicalTest-placeholder.png'),
  HOLIDAY: require('../assets/Images/holiday.png'),
  PDF: require('../assets/Images/pdf.png'),
  TEXT_FILE: require('../assets/Images/txt-file.png'),
  SHEET: require('../assets/Images/sheets.png'),
  ZIP: require('../assets/Images/zip.png'),
  FOLDER: require('../assets/Images/folder.png'),
  SPLASH_LOGO: require('../assets/Images/logoSquare.png'),
  DEFAULT_IMAGE: require('../assets/Images/default_img.png'),
  LOGO_DARK: require('../assets/ApplicationImage/logo-dark.png'),
  LOGO_REGULAR: require('../assets/ApplicationImage/logo-regular.png'),
};
